### ISSUE TITLE
[BUG] !github-reset errors out if the user isn't in the org.

### ISSUE THREAD

**Issue by Morpheus636** [PercyJackson235/StudyBot#4]
The !github-reset command errors out if the user that has been invited is in not in the org at the time of the reset command

This means that if the user 
1) left the org, and wants to re-join
2) the invite failed on github's end
3) the invite timed out

then the command does not reset their db entry, and so they still cannot invite themselves.

**Comment by PercyJackson235** [comment]
I have slightly better error reporting for this issue. I am not closing this issue just in case there is more to this issue if it is reproduced in production.
